GSTS/Controllers/GastoController.cs
using AutoMapper;
using GSTS.BaseDeDatos;
using GSTS.models.Gastos;
using GSTS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GSTS.Controllers
{
    public class GastoController : Controller
    {
        private GSTScontext _ctx;
        public GastoController()
        {
            _ctx = new GSTScontext();
        }

        // GET: Gasto
        public ActionResult Index()
        {

            var listado =  _ctx.Gastos.ToList();
            List<GastosViewModel> glv = Mapper.Map<List<GastosViewModel>>(listado);
            
            return View(glv);
        }

        // GET: Gasto/Details/5
        public ActionResult Details(int id)
        {
            var vm = ObtainViewModel(new GastosViewModel() { Id = id });
            return View("Create",vm);
        }

        // GET: Gasto/Create
        public ActionResult Create(GastosViewModel vm = null)
        {
            if(vm == null)
            {
                vm = new GastosViewModel();
            }
            vm = ObtainViewModel(vm);
            return View(vm);
        }

        // POST: Gasto/Create
        [HttpPost]
        public ActionResult Update(GastosViewModel vm)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View("Create", vm);
                }

                Gasto g = Mapper.Map<Gasto>(vm);
                _ctx.Entry(g).State = System.Data.Entity.EntityState.Modified;
                _ctx.SaveChanges();

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View("Create",vm);
            }
        }

        // GET: Gasto/Edit/5
        public ActionResult Edit(int id)
        {
            var vm = ObtainViewModel(new GastosViewModel() { Id = id });

            return View("Create",vm);
        }

        // POST: Gasto/Edit/5
        [HttpPost]
        public ActionResult Insert(GastosViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Create", vm);
                }

                Gasto g = Mapper.Map<Gasto>(vm);
                _ctx.Entry(g).State = System.Data.Entity.EntityState.Added;
                _ctx.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Gasto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Gasto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public GastosViewModel ObtainViewModel(GastosViewModel vm = null)
        {
            if(vm==null)
            {
                vm = new GastosViewModel();
            }else
            {
                if(vm.Id != 0)
                {
                    vm = Mapper.Map<GastosViewModel>(_ctx.Gastos.Find(vm.Id));
                }
            }

            vm.slTipoGastos = Mapper.Map<List<SelectListItem>>(_ctx.TipoGasto.ToList());
            return vm;

        }
    }
}

GSTS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GSTS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GSTS/Controllers/TipoGastoController.cs
using AutoMapper;
using GSTS.BaseDeDatos;
using GSTS.models.Gastos;
using GSTS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GSTS.Controllers
{

    

    public class TipoGastoController : Controller
    {
        private GSTScontext _ctx;
        public TipoGastoController()
        {
            _ctx = new GSTScontext();
        }

        // GET: TipoGasto
        public ActionResult Index()
        {
            var list =_ctx.TipoGasto.ToList();
            List<TipoGastoViewModel> lvm = Mapper.Map<List<TipoGastoViewModel>>(list);
            
            return View(lvm);
        }

        // GET: TipoGasto/Details/5
        public async Task<ActionResult> Details(int id)
        {
            TipoGasto entidad = await _ctx.TipoGasto.FindAsync(id);
            if(entidad == null)
            {
                return View("Error");
            }
            TipoGastoViewModel vm = Mapper.Map<TipoGastoViewModel>(entidad);
            return View("Create",vm);
        }

        // GET: TipoGasto/Create
        public ActionResult Create(TipoGastoViewModel vm = null)
        {
            if(vm==null)
            {
                vm = new TipoGastoViewModel();
            }
            
            return View(vm);
        }

        // POST: TipoGasto/Create
        [HttpPost]
        public ActionResult Insert(TipoGastoViewModel vm)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View("Create", vm);
                }

                TipoGasto entidad = Mapper.Map <TipoGasto>(vm);
                _ctx.Entry(entidad).State = System.Data.Entity.EntityState.Added;
                _ctx.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Update(TipoGastoViewModel vm)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Create", vm);
                }

                TipoGasto entidad = Mapper.Map<TipoGasto>(vm);
                _ctx.Entry(entidad).State = System.Data.Entity.EntityState.Modified;
                _ctx.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create",vm);
            }
        }


        // GET: TipoGasto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TipoGasto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoGasto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TipoGasto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GSTS/Views/Gasto/Create.cshtml
@model GSTS.ViewModel.GastosViewModel

@{
    ViewBag.Title = "Create";
    string method = Model.Id == 0 ? "Insert" : "Update";
}

<h2>Create</h2>


@using (Html.BeginForm(method,"Gasto",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()

   
        @Html.HiddenFor(m => m.Id);
    

    <div class="form-horizontal">
        <h4>GastosViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipoGastoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoGastoId, Model.slTipoGastos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoGastoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Fecha,"{0:dd/MM/yyyy}" ,new { htmlAttributes = new { @class = "form-control" } , data_fecha = "true" })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Importe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Importe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Importe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@method class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    
    <script>
        
            $(function () {
               
                OverrideMethodsJquery();
                AddDatepickers();
            });

        function OverrideMethodsJquery() {
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD/MM/YYYY", true).isValid();
            }

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            }

        }
        function AddDatepickers() {
            var ent = $("[data-fecha=true]");
            ent.datepicker({
                format: 'dd/mm/yyyy',
                location:'es'
                });
            console.log(ent);
        }

       
    </script>
}

GSTS/Views/Gasto/Index.cshtml
@model IEnumerable<GSTS.ViewModel.GastosViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipoGastoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Importe)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TipoGasto.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Importe)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

GSTS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GSTS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GSTS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GSTS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GSTS/Views/TipoGasto/Create.cshtml
@model GSTS.ViewModel.TipoGastoViewModel

@{
    ViewBag.Title = "Create";
    string method = Model.Id == 0 ? "Insert" : "Update";
}

<h2>Create</h2>


@using (Html.BeginForm(method,"TipoGasto",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    if(Model.Id != 0)
    {
        @Html.HiddenFor(x=>x.Id)
    }

    <div class="form-horizontal">
        <h4>TipoGastoViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@method class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GSTS/Views/TipoGasto/Index.cshtml
@model IEnumerable<GSTS.ViewModel.TipoGastoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>